# Generated by Django 5.2.7 on 2025-11-23 23:56

import apps.missionaries.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missionaries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='missionary',
            name='photo_scale',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='missionary',
            name='photo_translate_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='missionary',
            name='photo_translate_y',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='missionary',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.missionaries.models._upload_to_path),
        ),
    ]
