# Nginx configuration file
# Reference: https://docs.gunicorn.org/en/stable/deploy.html

worker_processes 1;

http {
    # fallback in case we can't determine a type
    include       mime.types;
    default_type  application/octet-stream;
    sendfile      on;

    upstream app_server {
        # fail_timeout=0 means we always retry an upstream even if it failed
        # to return a good HTTP response
        server 127.0.0.1:8000 fail_timeout=0;
    }

    server {
        # if no Host match, close the connection to prevent host spoofing
        listen 80 default_server;
        return 444;
    }

    server {
        server_name {domain};  # This domain value is replaced during deployment.
        listen 80 deferred;
        client_max_body_size 25M;

        location /static/ {
            alias /home/app-user/called/instance/staticfiles/;
        }

        location /media/ {
            alias /home/app-user/called/instance/media/;
        }

        location / {
            proxy_pass http://app_server;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
