# Nginx configuration file
# To debug, run: nginx -t

server {
    server_name {domain_name};  # This domain value is replaced during deployment.
    listen 80 deferred;
    client_max_body_size 25M;

    # Trying to use whitenoise for static files...
    # location /static/ {
    #     alias /home/app-user/called/instance/staticfiles/;
    # }

    location /media/ {
        alias /home/app-user/called/instance/media/;
    }

    location / {
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
