#cloud-config

# Automatic server configuration using cloud-init.
# Documentation: https://cloudinit.readthedocs.io/en/latest/
# Server logs at:
# /var/log/cloud-init.log
# /var/log/cloud-init-output.log

# This file is a template. Curly brace values are replaced with a call to
# Python's str.format before this file is sent to the cloud-init service.

users:
  - name: root
    lock_passwd: true           # Disable password-based login for root.

  - name: app-user
    gecos: Application User

package_update: true
package_upgrade: true
packages:
  - curl
  - git
  - nginx
  - ufw
  - snap:
    - [certbot, --classic]

write_files:
  - path: /home/app-user/called/.env
    owner: app-user:app-user
    permissions: '600'
    content: |
      DJANGO_DEBUG=False
      DJANGO_ALLOWED_HOSTS={domain_name}
      DJANGO_SECRET_KEY={secret_key}

runcmd:
  # Clone the repository as app-user.
  - su - app-user -c 'git clone https://github.com/genericmoniker/called.git $HOME/called'

  # Run initial setup scripts that are in the repository.
  - su - app-user -c '$HOME/called/deployment/server/update-app-user.sh'
  - /home/app-user/called/deployment/server/update-root.sh {domain_name}

  # Obtain and install SSL certificates using Certbot.
  - certbot --nginx -d {domain_name} -n --agree-tos -m {admin_email}

final_message: "The server setup is complete."
