#cloud-config

# Automatic server configuration using cloud-init.
# Documentation: https://cloudinit.readthedocs.io/en/latest/
# Server logs at:
# /var/log/cloud-init.log
# /var/log/cloud-init-output.log
# Schema validation on the server with:
# cloud-init schema --system

# This file is a template. Curly brace values are replaced with a call to
# Python's str.format before this file is sent to the cloud-init service.
# Look for the "Replace placeholders" comment in deployment/server/do-deploy.py.

users:
  - name: root
    # Disable password-based login for root (being verbose; this is the default for cloud-init).
    lock_passwd: true

  - name: app-user
    gecos: Application User
    lock_passwd: true
    shell: /bin/bash
    ssh_authorized_keys:
      - {app_user_ssh_key}

package_update: true
package_upgrade: true
packages:
  - curl
  - git
  - nginx
  - ufw
  - snap:
    - [certbot, --classic]

write_files:
  # Create the production.env file for the Django application.
  # This .env file is referenced by the systemd service file.
  - path: /home/app-user/.config/called/production.env
    owner: app-user:app-user
    permissions: '600'
    content: |
      DJANGO_DEBUG=False
      DJANGO_ALLOWED_HOSTS={domain_name}
      DJANGO_SECRET_KEY={secret_key}
      SENTRY_DSN={sentry_dsn}

runcmd:
  # Fix ownership of directories created by write_files.
  - chown -R app-user:app-user /home/app-user

  # Try to get journald to use the correct /etc/machine-id file.
  # Otherwise journalctl will say, "No journal files were found" despite logs being present.
  - systemd-machine-id-setup
  - systemctl restart systemd-journald

  # Enable lingering for app-user so systemd user services can run without a user session.
  - loginctl enable-linger app-user

  # Clone the repository as app-user.
  - su - app-user -c 'git clone https://github.com/genericmoniker/called.git $HOME/called'

  # Run initial setup scripts that are in the repository.
  - su - app-user -c '$HOME/called/deployment/server/update-app-user.sh'
  - /home/app-user/called/deployment/server/update-root.sh {domain_name}

  # Obtain and install SSL certificates using Certbot.
  - certbot --nginx -d {domain_name} -n --agree-tos -m {admin_email}

final_message: "The server setup is complete (cloud-config.yaml done)."
